In [2]:
import numpy as np

In [8]:
np.zeros((3, 4, 2), dtype = str)

array([[['', ''],
        ['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', ''],
        ['', '']],

       [['', ''],
        ['', ''],
        ['', ''],
        ['', '']]], dtype='<U1')

In [9]:
np.ones((5, 6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [14]:
np.random.seed(10)
np.random.random((10, 4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715],
       [0.90864888, 0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632, 0.62628715]])

In [15]:
np.random.seed(10)
np.random.randint(10, 20, size = (2, 4))

array([[19, 14, 10, 11],
       [19, 10, 11, 18]], dtype=int32)

In [22]:
# same as random
np.random.seed(10)  # задать начальное зерно
np.random.uniform(10.0, 50.0, size=(3, 5))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 , 29.94028049],
       [18.99186582, 17.92251459, 40.42122849, 16.76443346, 13.53359257],
       [37.41439273, 48.13573385, 10.15793065, 30.48769054, 42.50483847]])

In [19]:
np.random.seed(10)

In [21]:
np.random.choice(np.array([1, 2, 3]), size=20)

array([2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 3, 1, 2, 1, 3, 1, 3, 1, 1, 1])