In [3]:
import numpy as np

##  1. Calculating Total Revenue

In [4]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [5]:
quantitis = np.array([10, 5, 8, 12, 3])
quantitis

array([10,  5,  8, 12,  3])

In [7]:
revenue_per_product = prices * quantitis
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [9]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [10]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [12]:
max_views = np.max(views)
max_views

np.int64(1200)

In [13]:
min_views = np.min(views)
min_views

np.int64(300)

In [16]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(733.33)

In [17]:
total_views = np.sum(views)
total_views

np.int64(4400)