In [2]:
import numpy as np

##  1. Calculating Total Revenue

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantitis = np.array([10, 5, 8, 12, 3])
quantitis

array([10,  5,  8, 12,  3])

In [5]:
revenue_per_product = prices * quantitis
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [6]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [7]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [8]:
max_views = np.max(views)
max_views

np.int64(1200)

In [9]:
min_views = np.min(views)
min_views

np.int64(300)

In [10]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(733.33)

In [11]:
total_views = np.sum(views)
total_views

np.int64(4400)

## 3. Splitting Order into Batches

In [15]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [16]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [21]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}")
    print("First Element in the batch:", batch[0])
    print("Second Element in the batch:", batch[1])
    print("")

Batch number 0
First Element in the batch: 1001
Second Element in the batch: 1002

Batch number 1
First Element in the batch: 1003
Second Element in the batch: 1004

Batch number 2
First Element in the batch: 1005
Second Element in the batch: 1006

Batch number 3
First Element in the batch: 1007
Second Element in the batch: 1008



## 4. Categorizing Product Ratings

In [22]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [24]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [25]:
negative_ratings = ratings[ratings <= 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total and Average quantities sold

In [27]:
# Each column is specific product (we have 4 products)
# Each row is specific order (we have to orders)
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3,9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [31]:
# Quantities of the sales per product
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [34]:
# Average quantities per product across all orders
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate Average product Rating and Maximum raating per Category

In [38]:
# Each row is one product
# Each product is rated in 4 categories
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [41]:
# Average rating in each category
avarage_rating_per_category = np.mean(product_ratings, axis=0)
avarage_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [43]:
# Average rating in each product
avarage_rating_per_product = np.mean(product_ratings, axis=1)
avarage_rating_per_product

array([3.8  , 3.475, 2.7  ])

In [46]:
# Maximum rating in each product
max_rating_per_product = np.max(product_ratings, axis=0)
max_rating_per_product

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of the sample stock data

In [47]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'True 2 April']
price_types = ['Open', 'Close', 'Hight', 'Low']

In [49]:
# shape will be (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [50]:
stock_prices.shape

(3, 2, 4)

In [53]:
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for the {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day}')
        for index_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}')
        print('')
    print('')

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
Hight Price: 0.0
Low Price: 0.302

Day: True 2 April
Open Price: 0.147
Close Price: 0.092
Hight Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
Hight Price: 0.419
Low Price: 0.685

Day: True 2 April
Open Price: 0.204
Close Price: 0.878
Hight Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
Hight Price: 0.14
Low Price: 0.198

Day: True 2 April
Open Price: 0.801
Close Price: 0.968
Hight Price: 0.313
Low Price: 0.692


