In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(15, 25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
np.arange(20, 30, 3)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(-20, 30, 4)

array([-20, -16, -12,  -8,  -4,   0,   4,   8,  12,  16,  20,  24,  28])

In [7]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [10]:
np.arange(20).reshape([2, 2, 5]).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [11]:
np.random.random((10, ))

array([0.19230506, 0.5381017 , 0.38611606, 0.20517514, 0.15987108,
       0.1297335 , 0.70590845, 0.18590158, 0.63657088, 0.28529583])

In [13]:
np.random.seed(10)
np.random.random((10, )).reshape([2, 5])

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [14]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]], dtype=int32)

In [16]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69], dtype=int32)

In [ ]:
np.arange(30).reshape